# .cnb.yml
include:
  - https://cnb.cool/kevisual/cnb/-/blob/main/.cnb/template.yml

.common_env: &common_env
  env:
    USERNAME: root
  imports:
    - https://cnb.cool/kevisual/env/-/blob/main/.env.development

$:
  vscode:
    - docker:
        image: docker.cnb.cool/kevisual/dev-env:latest
      services:
        - vscode
        - docker
      imports: !reference  [.common_env, imports]
      stages: !reference  [.dev_template, stages]